# Generated by Django 5.0.1 on 2026-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[("free", "Free"), ("professional", "Professional"), ("enterprise", "Enterprise")],
                        default="free",
                        max_length=50,
                    ),
                ),
                ("subscription_expiration", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending_deletion", "Pending Deletion"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tenants",
                "indexes": [models.Index(fields=["status"], name="idx_tenants_status")],
            },
        ),
    ]
