# Generated by Django 5.0.1 on 2026-03-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tenant',
            name='check_subscription_tier',
        ),
        migrations.RemoveConstraint(
            model_name='tenant',
            name='check_status',
        ),
    ]
