# Generated by Django 5.0.1 on 2026-03-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(role__in=["admin", "user", "read_only"]), name="check_role"
            ),
        ),
    ]
