# Generated by Django 5.0.1 on 2026-03-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_constraints'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='check_role',
        ),
    ]
